### ISSUE TITLE
Document the --configure behavior

### ISSUE THREAD

**Issue by khenidak** [noelbundick/azure-cli-extension-noelbundick#10]
Well since we are using the same tenant the `--configure` (with default params) failed. Might be a good idea to 

1- Generate random (tag it if supported by sp that created it)
2- Warn the user of this dup situation

**Comment by noelbundick** [comment]
Thx for docs note - agree!

Can you give more detail on how it failed? It's calling `az ad sp create-for-rbac` under the hood w/o params - which should generate unique-ish names

I guess it could fail if two people in your tenant created an SP at the same time, and there was a name conflict on `azure-cli-2018-06-06-21-09-43`

Might also be another Python 2 error - will check!

**Comment by khenidak** [comment]
I got `object already exists`. Sorry didn't capture the exact error. It worked when i manually created my sp, applied role to the subscription and used `--configure --client_id xxx --client_secret`

**Comment by noelbundick** [comment]
Added a [self-destruct mode](https://github.com/noelbundick/azure-cli-extension-noelbundick/blob/master/docs/self-destruct.md) doc in [v0.0.10](https://github.com/noelbundick/azure-cli-extension-noelbundick/releases/tag/v0.0.10)
