### ISSUE TITLE
az shell ssh broken

### ISSUE THREAD

**Issue by isaac2004** [noelbundick/azure-cli-extension-noelbundick#34]
I installed the extension and when I run

```
az shell ssh
```
I get this error

![image](https://user-images.githubusercontent.com/8878502/57320665-6664cf00-70cd-11e9-8176-15a3058c001d.png)

**Comment by noelbundick** [comment]
Thanks for the bug report! This is now fixed in [v0.0.15](https://github.com/noelbundick/azure-cli-extension-noelbundick/releases/tag/v0.0.15)
