### ISSUE TITLE
logic app cleanup?

### ISSUE THREAD

**Issue by colemickens** [noelbundick/azure-cli-extension-noelbundick#8]
Does the Logic App self-clean-up as well? Or is the cost negligible enough that it doesn't matter if they hang around?

**Comment by noelbundick** [comment]
Yeah, it sure does!

Relevant bits are the DeleteSelf action in https://github.com/noelbundick/azure-cli-extension-noelbundick/blob/master/src/noelbundick/azext_noelbundick/self_destruct_template.json#L67

Logic apps are pay-per-execution, so the cost for this is $0.000050 (2 actions at the base rate in WestUS2).

Technically, Logic Apps doesn't support one-time triggers, so I've set a Recurrence trigger with a start date, and reoccurs once every 16mo (the longest interval). So - totally a hack, but, even if something wen horribly wrong, it won't cost you more than fractions of a cent once every couple of years

**Comment by noelbundick** [comment]
Added additional details in the [self-destruct mode](https://github.com/noelbundick/azure-cli-extension-noelbundick/blob/master/docs/self-destruct.md) doc
